Uploading all exercises from Module 5 - Arrays
cywka333/Devsmentoring-java pull request #1
Opened 2022-11-08 16:19 UTC by cywka333

2022-11-16 05:53 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module5/Exercise08.java
> +            if (firstCounting >= 100) {
Ten warunek będzie nam też zliczał 4-ro cyfrowe liczby itd?

2022-11-16 05:54 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module5/Exercise08.java
> +        byte threeNumbersInSecondArray = 0;
Nazwałbym to three**Digit**NumbersInFirstArray

2022-11-16 05:54 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module5/Exercise08.java
> +        byte threeNumbersInSecondArray = 0;
Zastanowiłbym się też nad typem danych

2022-11-16 05:58 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module5/Exercise09.java
> +    public static void main(String[] args) {
Dobrze, spoko wymyśliłeś z wypełnianiem tablicy wartościami

2022-11-16 06:00 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module5/Exercise10.java
> +public class Exercise10 {
Fajnie wyświetla :)
![image](https://user-images.githubusercontent.com/36398500/202096600-d8257443-b12c-4a85-bacb-31842ab9da31.png)

2022-11-16 06:01 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module5/Exercise10.java
> +        int[][] newTab = new int[10][3];
pomyślałbym nad inną nazwą zmiennej, żeby bardziej nam mówiła co ona przechowuje

2022-11-16 06:02 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module5/Exercise10.java
> +                System.out.print("    ");
Czy ten sout jest potrzebny?

2022-11-16 06:03 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module5/Exercise10.java
> +                System.out.print("[" + j + "]" + "[" + k + "]" + " = " + newTab[j][k] + "   ");
Czy "]" + " = " można by połączyć w jednego Stringa?

2022-11-16 06:10 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module5/Exercise11.java
> +        List<String> names = new ArrayList<>(Arrays.stream(numbers2D).flatMap(Arrays::stream).toList());
Fajnie, że wyszukałeś, że jest coś takiego jak stream-y, faktycznie używa się ich do operowania na tablicach/kolekcjach -> możemy spojrzeć na sesji jak je można wykorzystać w tym zadaniu, na razie jednak spróbuj bez korzystania ze streamów

2022-11-16 06:11 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module5/Exercise11.java
> +        for (int i = 0; i < names.size(); i++) {
Czy musimy modyfikować listę, tj. usuwać z niej - może byłoby łatwiej pominąć elementy których nie chcemy wyświetlać?

2023-01-13 12:57 UTC, kpuda requested changes

2023-01-13 12:57 UTC, kpuda commented on src/pl/devsmentoring/java/Module5/Exercise13.java
> +            newList.add(scanner.nextLine());
if user passes "STOP" it will be added to the list. You have to check word before adding it to the list.

2023-01-13 12:57 UTC, kpuda commented on src/pl/devsmentoring/java/Module5/Exercise17.java
> +        for (int i = 0; i <= i + 1; i++) {
for loop is used to make finite loop in definition. If You want to make infinite loop - cast while/do while

2023-01-13 12:57 UTC, kpuda commented on src/pl/devsmentoring/java/Module5/Exercise17.java
> +            }else if (!playList.containsKey(userChoice)){
it is unnecessaryy to call else if with the same condition, but reversed. Just call else

2023-01-13 12:57 UTC, kpuda commented on src/pl/devsmentoring/java/Module5/Exercise18.java
> +        for (int i = 0; i <= i; i++) {
same as above

2023-01-13 12:57 UTC, kpuda commented on src/pl/devsmentoring/java/Module5/Exercise18.java
> +            } else if (!playList.containsKey(userChoice)) {
same as above

2023-01-13 12:57 UTC, kpuda commented on src/pl/devsmentoring/java/Module5/Exercise20.java
> +        System.out.println("In the list we have: " + colourAsValues.size() + " different colours.\n");
you have to count number of colors. for example czerwony=2

2023-01-20 07:39 UTC, kpuda requested changes

2023-01-20 07:39 UTC, kpuda commented on src/pl/devsmentoring/java/Module5/Exercise20.java
> +        int indygoCounter = Collections.frequency(colourList, "indygo");
jakbyśmy dodali przykładowo kolor żółty to musielibyśmy znów przerabiać pod to kod. 

Podpowiedź: Zrób mapę gdzie kluczem będzie kolor (czyli String), a wartością Integer (czyli ilość). Loopując przez listę dodajesz kolory do mapy, jeśli taki kolor już istnieje - iterujesz wartość o 1

2023-01-23 09:12 UTC, kpuda requested changes

2023-01-23 09:12 UTC, kpuda commented on src/pl/devsmentoring/java/Module5/Exercise20.java
> +            colorCounts.put(color, colorCounts.get(color) + 1);
tutaj najpierw wrzucasz kolor, a później dodajesz do niego 1.

Przekształć to w taki sposób żeby najpierw dochodziło do instrukcji warunkowej gdzie sprawdzasz czy istnieje taki kolor w mapie. Jeśli nie istnieje - dodajesz go do mapy z wartością 1. Jeśli istnieje, inkrementujesz jego wartość

2023-01-23 09:12 UTC, kpuda commented on src/pl/devsmentoring/java/Module5/Exercise20.java
> +        Set<String> colourAsValues = new HashSet<>(colourList);
już nie potrzebujesz deklarować setów. W zadanku raczej chodziło o to żebyś spróbował do początkowej listy dodać jakiś kolor i zobaczyć jak zmieni się program

2023-01-26 12:57 UTC, kpuda commented on src/pl/devsmentoring/java/Module5/Exercise20WithMethods.java
> +    private static HashSet<String> colourSet = new HashSet<>();
wydaje mi się, że w tej wersji z metodami to robiliśmy to zajęciach w oparciu o hashmapę i dlatego wspominaliśmy wtedy o metodach

2023-01-31 16:38 UTC, kpuda approved these changes

2023-01-31 19:05 UTC, merged