Module 7
cywka333/Devsmentoring-java pull request #2
Opened 2022-11-27 15:51 UTC by cywka333

Exercise from Module 7 are done.

2022-11-28 18:05 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module7/Exercise09/Deck.java
> +        this.deck = new ArrayList<Card>(allSuits.length * allRanks.length);
Czy musimy przekazywać rozmiar listy w konstruktorze?

2022-11-28 18:14 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module7/Exercise09/Deck.java
> +        return deck.remove(51);
Czy da się to zrobić bardziej dynamiczne - co np. kiedy będziemy mieli inną liczbę kart w talii?

2022-11-28 18:14 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module7/Exercise09/Deck.java
> +    public boolean isEmpty(){
Czy potrzebujemy tej metody?

2022-11-28 18:17 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module7/Exercise09/Deck.java
> +public class Deck {
Brakuje metody do losowania karty?

2022-11-28 18:19 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module7/Exercise09/Rank.java
> +public enum Rank {
Fajnie, że z enumem zrobiłeś :)

2022-11-28 18:19 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module7/Exercise09/Rank.java
> +    KING(10, "K"),
Ta sama wartość przy tych kartach?

2022-11-28 18:50 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module7/Exercise12/Manager.java
> +            if (userIdInput == order1.getId() || userIdInput == order2.getId() || userIdInput == order3.getId()) {
Jak to obsłuzymy jak będziemy mieli jeszcze więcej zamówień, już np. w setkach?

2022-11-28 18:52 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module7/Exercise12/Manager.java
> +                        break;
Możemy spróbować bardziej generycznie - 59-62 mamy podobną logikę

2022-11-28 18:54 UTC, szymonstuszek commented on src/pl/devsmentoring/java/Module7/Exercise12/Manager.java
> +            }
Można się zastanowić nad np. do while-m, żeby obsługiwać poprawny/niepoprawny input

2023-01-13 13:02 UTC, kpuda requested changes

2023-01-13 13:02 UTC, kpuda commented on src/pl/devsmentoring/java/Module7/Exercise12/Manager.java
> +
Manager should be just a class with parameters and methods. You should extract creating objects etc. to e.g Main.Class

2023-01-19 10:34 UTC, kpuda approved these changes

2023-01-19 10:34 UTC, kpuda commented on src/pl/devsmentoring/java/Module7/Exercise12/Main.java
> +        Order order4 = new Order(4, "Headphones", 200.00);
super!

2023-01-31 16:38 UTC, kpuda approved these changes

2023-01-31 19:05 UTC, merged