I did all exercises from Module 8.
cywka333/Devsmentoring-java pull request #3
Opened 2023-01-13 11:04 UTC by cywka333

2023-01-29 12:42 UTC, kpuda requested changes

2023-01-29 12:42 UTC, kpuda commented on src/pl/devsmentoring/java/Module8/Exercise8/MessagingSystem.java
> +package pl.devsmentoring.java.Module8.Exercise8;
po klasie messagingSystem klasy Info oraz Warning powinny dziedziczyć tak aby pozbyć się duplikatu kodu. Stwórz dodatkowo klasę Zad8.java gdzie zamieścisz psvm

2023-01-29 12:42 UTC, kpuda commented on src/pl/devsmentoring/java/Module8/Exercise6/Address.java
> +public class Address {
address ma tylko pusty konstruktor. Nie jest możliwe podanie żadnych wartości

2023-01-29 12:42 UTC, kpuda commented on src/pl/devsmentoring/java/Module8/Exercise6/Main.java
> +
Trzeba przetestować czy działa :D

2023-01-29 12:42 UTC, kpuda commented on src/pl/devsmentoring/java/Module8/Exercise6/Person.java
> +    public Person(Address address, String name, String phoneNumber, String emailAddress) {
żeby osiągnąć agregację należałoby jeszcze dodać konstruktor bez adresu

2023-01-29 12:42 UTC, kpuda commented on src/pl/devsmentoring/java/Module8/Exercise6/Professor.java
> +    private void execute(){
to nie jest nigdzie wykorzystywane

2023-01-29 12:42 UTC, kpuda commented on src/pl/devsmentoring/java/Module8/Exercise6/Student.java
> +    public void execute(){
to nie jest nigdzie wykorzystywane

2023-01-29 12:42 UTC, kpuda commented on src/pl/devsmentoring/java/Module8/Exercise4/Tram.java
> +        if (wagonNo >= 1 && wagonNo <= 3){
fajnie, że pomyślałeś o takim sprawdzeniu!

2023-01-29 12:42 UTC, kpuda commented on src/pl/devsmentoring/java/Module8/Exercise4/TramDepot.java
> +        Tram tram1 = new Tram(100,3,4);
Takie rzeczy wyrzucamy do np. Main!!!!

2023-01-29 12:42 UTC, kpuda commented on src/pl/devsmentoring/java/Module8/Exercise4/BusDepot.java
> +        Bus bus1 = new Bus(200, 2, 5000);
Takie rzeczy wyrzucamy do np. Main!!!!

2023-01-29 12:42 UTC, kpuda commented on src/pl/devsmentoring/java/Module8/Exercise4/BusDepot.java
> +        int fuelMonthlyUsage;
najlepiej byłoby stworzyć klasę Depot, po której busdepot oraz tramdepot dziedziczą

2023-01-29 12:42 UTC, kpuda commented on src/pl/devsmentoring/java/Module8/Exercise2/Shape.java
> +    protected int a = 0;
brak konstruktora. Jak utworzymy jakikolwiek obiekt?

2023-01-29 12:42 UTC, kpuda commented on src/pl/devsmentoring/java/Module8/Exercise2/Square.java
> +    private int length;
niepotrzebna zmienna. Wykorzystaj dziedziczenie

2023-01-29 12:42 UTC, kpuda commented on src/pl/devsmentoring/java/Module8/Exercise2/Square.java
> +    public Square (int length){
ten konstruktor powinien nadawać wartość odziedziczonym polom

2023-02-01 10:40 UTC, cywka333 commented
After yesterday's refactoring I merge this branch to main.

2023-02-01 10:41 UTC, merged